server:
  port: 9002

spring:
  application:
    name: tensquare-recruit
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.24.56.191:3305/tensquare_recruit?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: MySql
    show-sql: true
